### ISSUE TITLE
[Bug] Cursor position is not proper after using inc/dec buttons

### ISSUE THREAD

**Issue by GAM3RG33K** [Abhilash-Chandran/number_inc_dec#37]
Issue:
I am using this plugin to take user input for a demo.

What I have observed is that once the input field gets focus it shows cursor properly. But after the cursor is visible if you use the increment & decrement buttons then the cursor moves in the center of the text.

It seems that it can be solved by removing the focus from text field when user clicks any of the buttons.
This is my take on the solution, but I do not know the reason behind this, so this might be the exact solution.

If you need more details regarding this issue then please tag me in the comments of this issue, I'll try to get back to you as soon as possible.

Code I used to create the input field with customizations:

```dart
NumberInputWithIncrementDecrement(
  controller: _controller,
  initialValue: _units,
  isInt: true,
  widgetContainerDecoration: BoxDecoration(
     borderRadius: BorderRadius.circular(5.0),
     border: Border.all(
     color: Color(0xFFE0E0E0),
     width: 2.0,
    ),
  ),
  onIncrement: _updateUnits,
  onDecrement: _updateUnits,
  autovalidate: true,
  validator: (value) {
            // code omitted
  },
 ),
```

Please check the attached video for reproduction steps:

https://user-images.githubusercontent.com/11572011/114990738-7343ed00-9eb6-11eb-87b9-a1f25aad8139.mp4

**Comment by Abhilash-Chandran** [comment]
@GAM3RG33K Thanks lot for reporting this issue 💯 👍 . I have already found and fixed this issue couple of months ago 😄 . 

https://github.com/Abhilash-Chandran/number_inc_dec/blob/c8aba28b05d2a58c88f7fa0273097c7a4cb39dae/lib/src/number_increment_decrement.dart#L542

I haven't released  this yet as I am busy with my thesis and also one major issue is pending for that release which involve increment based on steps and validation. However I will be free by end of May and will push a major release as early as possible. Hope its ok.

**Comment by GAM3RG33K** [comment]
@Abhilash-Chandran  

Hi, thanks for the quick response, If you have already resolved this issue then would you recommend using the master branch checkout? 

I need to resolve this for my app demo to client.

I will move to latest stable release of the plugin by next update.

**Comment by Abhilash-Chandran** [comment]
Unfortunately its in a different branch. So switching to Master won't help and I wouldn't recommend to switching to the branch with the fix either. Cause that has other issue merged in it. I am sorry about that 😞

**Comment by GAM3RG33K** [comment]
ok then, I'll wait for the plugin update. 

Anyway, thanks for creating this plugin it has saved me a significant amount time, I really appreciate it.

Great job.
