### ISSUE TITLE
onIncrement/onDecrement: 'Null Function()' can't be assigned to 'void Function(num)'. How to use?

### ISSUE THREAD

**Issue by cormalenv** [Abhilash-Chandran/number_inc_dec#4]
Unable to add any statement to `onIncrement` or `onDecrement`

Simple examples
`onIncrement: () {var myInt = 1}`
or
`onIncrement: () => myMethod(),`

results in

`The argument type 'Null Function()' can't be assigned to the parameter type 'void Function(num)'.`
and
`The argument type 'dynamic Function()' can't be assigned to the parameter type 'void Function(num)'.`

Can we get an example of how to use?? Is this right?

```
NumberInputWithIncrementDecrement(
                      controller: myTEC,
                      min: 1,
                      max: 10,
                      initialValue: 5,
                      onIncrement: myMethod(int.parse(myTEC)),
)
```

**Comment by Abhilash-Chandran** [comment]
This `TypeDefinition` for `onIncrement` and `onDecrement` callback is `DiffIncDecCallBack ` as in [here](https://pub.dev/documentation/number_inc_dec/latest/number_inc_dec/DiffIncDecCallBack.html). The call back should be a `void` method which wont return any value and should accept a parameter of type `num` which will the be incremented or decremented value depending on the scenario. Following is an example.

```dart
NumberInputWithIncrementDecrement(
                      controller: myTEC,
                      min: 1,
                      max: 10,
                      initialValue: 5,
                      onIncrement: (num newValue){
                           print('Newly incremented value is $newValue')
                      },
                      onDecrement: (num newValue){
                           print('Newly decremented value is $newValue');
                      },
)
```

Please check if this helps in your case. I will try add some more documentation for the relevant section in the upcoming release.

**Comment by cormalenv** [comment]
Thanks very much @Abhilash-Chandran!

**Comment by Abhilash-Chandran** [comment]
Glad it helped @cormalenv. Thanks for filing and closing the issue. Let me know if you need any other information. I am working on the documentation for the same.
